schema = 1

[image]
name = "lyra-os"
description = "kiwi"
architecture = "x86_64"
required_flavor = "standard"
optional_flavors = ["nvidia"]

[obs]
api_url = "https://api.opensuse.org"
project = "home:rodrigosbrito:lyra:images:staging"
package = "lyra-image"
repository = "images"
maintainer = "rodrigosbrito"

[[obs.paths]]
project = "home:rodrigosbrito:lyra"
repository = "openSUSE_Leap_16.0"

[[obs.paths]]
project = "home:rodrigosbrito:vega"
repository = "openSUSE_Leap_16.0"

[[obs.paths]]
project = "home:rodrigosbrito:fina"
repository = "openSUSE_Leap_16.0"

[[obs.paths]]
project = "Virtualization:Appliances:Builder"
repository = "openSUSE_Leap_16.0"

[artifacts]
required = ["iso", "packages", "verified", "changes", "kiwi_result"]
