# Lyra OS — fstab generation (§4)
---
mountOptions:
    default: defaults,noatime
    btrfs: defaults,noatime,compress=zstd:1,ssd,space_cache=v2
    btrfs_swap: defaults,noatime
ssdExtraMountOptions:
    btrfs: discard=async
crypttabOptions: luks
